server:
  port: 8081

telegram:
  # Ссылка или ID Telegram канала ParserBotTest
  channel: -1002451356715
  # Токен телеграм бота
  botToken: 7314567198:AAFjOVu22Rm16hxMhXQrQWAkhEnhHn_pUVU
  # Имя бота
  botUsername: WallEPCbot

vk:
  # Токен группы VK для использования LongPoll API
  tokenGroup: vk1.a.cEo1rZGWUieE0DzcGNyrzeulBk7A46wsyb9WteIc7gb3yHXkKOVS7JWBvpiLnL4LNs9nZaHMrqzfzsM0IfSKVyOmka1B69vNFBaGym_zmYabFAowteGG4WcZaAlnCehDs83N7NCLc-kbMm2-aOe_3rofXV1FyX_zjekvrsN8at1BuqZRo92goawUti_-xBvXuNo-G5pTEyFH-g27iUZTqA
  # Токен приложения VK
  serviceToken: K4EfUlnEty2vjTx1mq19
  #serviceToken: 173a6e10173a6e10173a6e10c0142540b21173a173a6e1071cfcb3a0261186f167264c2
  # Частичное название ссылки на VK канал (например, vk.com/example)
  domain: parcerbottest
  # ID группы
  groupID: -227662734
  # ID приложения
  appID: 52375202

filepath:
  lastPostID: "src/data/lastPostID.txt"

request:
  firstCount: 10 # Ограничение постов в минуту при первом запуске
  count: 5  # Количество постов (min = 2, max = 100)
  filter: OWNER  # Фильтр постов: "owner", "others", "all", "postponed", "suggests"

settings:
  timeToSleep: 600000  # Время ожидания между циклами (в миллисекундах) (10 минут)

  # для последующей доработки проекта

  # skipReposts: true  # Не парсить репосты
  # skipAudio # Не парсить аудио
  # skipVideo: true  # Не парсить видео
  # skipDocument: true # Не парсить документы

# filtering:
  # whitelist: '[]'  # Список слов для отбора постов
  # blacklist: '[]'  # Список слов для исключения постов

logging:
  level:
    root: INFO  # Уровень логирования для всех пакетов
    com.KarpiukJava: DEBUG  # Уровень логирования для вашего пакета
  file:
    path: ./logs/Vk2TgBot.log  # Путь до файла для сохранения логов
  logback:
    rollingpolicy:
      max-file-size: 10MB  # Максимальный размер лог-файла
      max-history: 14  # Количество лог-файлов, которые хранятся