# Working port for bot
server:
  port: 8081

telegram:
  # Link or ID of Telegram channel
  channel: # your channel ID with "-"
  # Telegram bot token
  botToken: #your Telegram bot token 
  # Имя бота
  botUsername: #your bot name

vk:
  # Personal access token, generated on website https://vkhost.github.io/
  accessToken: # yourAccessToken
  # group ID 
  groupID: # yourGroupID
  # Part name of the link of VK group (for example, vk.com/example)
  domain: # your VK domain name
  # ID of group administrator (ID of the person for whom the access token was generated)
  adminID: # ID of admin user

filepath:
  lastPostID: "./src/data/lastPostID.txt"

request:
  count: 3  # Number of posts in one pass (min = 2, max = 100)
  filter: OWNER  # Фильтр постов: "owner", "others", "all", "postponed", "suggests"

settings:
  timeToSleep: 60000  # Delay time between passes (1 minute in ms)

logging:
  level:
    root: INFO  # Logging level for all packages
    com.Vk2TgParser: DEBUG  # The logging level for your package
  file:
    path: ./logs/Vk2TgBot.log  # Path to file for saving logs
  logback:
    rollingpolicy:
      max-file-size: 10MB  # Max size of log-file
      max-history: 14  # Number of Log-files which are seved

  # For the future versions

  # skipReposts: true  
  skipAudio: true 
  skipPhoto: false 
  skipVideo: false 
  # skipDocument: true

  # filtering:
  # whitelist: '[]'  
  # blacklist: '[]'
